version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  python-app:
    build: .
    container_name: python_app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: tail -f /dev/null

volumes:
  postgres-data:
